Fix python relative imports with aliases
src-d/imports pull request #4
Opened 2019-11-23 00:07 UTC by kuba--

Signed-off-by: kuba-- <kuba@sourced.tech>

This PR fixes python relative imports with aliases, e.g.: `from a.b import x as b`
Now we check only first query which satisfies import, so in this case we check `import_from_statement` and don't check the next one `aliased_import`, what would append `x`.

2019-11-25 13:54 UTC, dennwc requested changes

2019-11-25 13:54 UTC, dennwc commented on languages/python/python.go
> +		if out := imports(content, root, qi); len(out) > 0 {
This is incorrect. You should append all results together. What if you have an import that matches the first query and the second import that matches the second query?

2019-11-25 13:54 UTC, dennwc commented on languages/python/python.go
> +		fnFilter = map[string]struct{}{
It should be a global.

2019-11-25 13:54 UTC, dennwc commented on languages/python/python_test.go
> +			Name: "relative named",
Please add a mixed test as well to cover my previous comment.

2019-11-25 22:06 UTC, kuba-- commented
Should be fixed, right now.

2019-11-26 14:08 UTC, dennwc approved these changes

2019-11-26 14:08 UTC, merged